language: node_js
node_js:
  - 9
services:
  - docker
cache:
  directories:
    - node_modules

script:
  - ./script/unittestweb
  - ./script/unittestapi
  - docker-compose -f compose/test/docker-compose.yml run e2e
  - sonar-scanner

addons:
  sonarcloud:
    organization: "poorprogrammer"
    token:
      secure: "2dc215dc3662ade4affa6af491ba49e3ca5c600c" # encrypted value of your token
