language: node_js
node_js:
  - lts/*
services:
  - docker
cache:
  directories:
    - api/node_modules
    - web/node_modules

script:
  - cd web && npm install
  - ./script/unittestweb
  # - ./script/unittestapi
  # - docker-compose -f compose/test/docker-compose.yml run e2e
  # - sonar-scanner

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3.7
  - python3 --version
  # - docker build -t poorprogrammer/cfo-web web
  # - docker build -t poorprogrammer/cfo-api api

# deploy:
#   provider: script
#   script: bash script/docker_push
#   on:
#     branch: master

# addons:
#   sonarcloud:
#     organization: "poorprogrammer"
#     token: ${SONAR_TOKEN}
