language: node_js
node_js:
  - 9
services:
  - docker
cache:
  directories:
    - node_modules

script:
  - ./script/unittestweb
  - docker-compose -f compose/test/docker-compose.yml run e2e
  - sonar-scanner

addons:
  sonarcloud:
    organization: "poorprogrammer"
    token:
      secure: "498b44a50aefdfc4545e1e37fd70ad82c16fab49" # encrypted value of your token
