language: node_js
python:
  - "3.7"
node_js:
  - lts/*
services:
  - docker
cache:
  directories:
    - api/node_modules
    - web/node_modules

script:
  - docker-compose -f compose/test/docker-compose.yml run unittestweb
  - ./script/unittestapi
  - docker-compose -f compose/test/docker-compose.yml run e2e
  - sonar-scanner

before_install:
  - docker build -t poorprogrammer/cfo-web web
  - docker build -t poorprogrammer/cfo-api api

deploy:
  provider: script
  script: bash script/docker_push
  on:
    branch: master

addons:
  sonarcloud:
    organization: "poorprogrammer"
    token: ${SONAR_TOKEN}
