services:
  keycloak:
    build:
      context: .
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9000:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/odds"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - cfo
networks:
  cfo:
