services:
  keycloak:
    extends:
      file: ../keycloak/docker-compose.yml
      service: keycloak
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - cfo

  api:
    build:
      context: ../../api
    command: /app/scripts/start_api_with_test_fixture
    ports:
      - "3000:3000"
    networks:
      - cfo

  web:
    build:
      context: ../../web
      args:
        # - VUE_APP_BASE_API=http://api:3000
        # - VUE_APP_KEYCLOAK_URL=http://keycloak:8080
        - VUE_APP_BASE_API=http://host.docker.internal:3000
        - VUE_APP_KEYCLOAK_URL=http://host.docker.internal:9000
        - VUE_APP_KEYCLOAK_REALM=odds
        - VUE_APP_KEYCLOAK_CLIENT_ID=cfo
    ports:
      - "8080:8080"
    networks:
      - cfo
    depends_on:
      api:
        condition: service_started
      keycloak:
        condition: service_healthy

  e2e:
    build:
      context: ../../e2e
    environment:
      - PLAYWRIGHT_TEST_BASE_URL=http://host.docker.internal:8080
    volumes:
      - ../../e2e/test-results:/app/test-results
      - ../../e2e/playwright-report/:/app/playwright-report
    # command: npx playwright test
    command: bash
    depends_on:
      web:
        condition: service_started
    networks:
      - cfo

  e2e_cucumber:
    build:
      context: ../../e2e
    command: npm run test:cucumber
    depends_on:
      - web
    networks:
      - cfo
networks:
  cfo:
