services:
  api:
    build:
      context: ../../api
    command: /app/scripts/start_api_with_test_fixture
    networks:
      - cfo

  web:
    build:
      context: ../../web
      args:
        - VUE_APP_BASE_API=http://api:3000
    command: serve -s -L /app -p 8080
    networks:
      - cfo
    depends_on:
      - api

  e2e:
    build:
      context: ../../e2e
    command: npx playwright test
    depends_on:
      - web
    networks:
      - cfo

  e2e_cucumber:
    build:
      context: ../../e2e
    command: npm run test:cucumber
    depends_on:
      - web
    networks:
      - cfo
networks:
  cfo:
