name: poorprogrammer/cfo-api

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run web unit tests
        run: ./script/unittestweb
