name: CFO CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.5.1]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install web dependencies
        run: yarn install
        working-directory: web

      - name: Run web unit test
        run: make test-web-ci

      - name: Install api dependencies
        run: yarn install
        working-directory: api

      - name: Run api unit test
        run: ./runtests.md
        working-directory: api

      - name: run e2e tests (playwright)
        run: docker compose -f compose/test-ci/docker-compose.yml run e2e

      - name: run e2e tests (cucumber)
        run: docker compose -f compose/test-ci/docker-compose.yml run e2e_cucumber

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push web
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poorprogrammer/cfo-web
          context: "{{defaultContext}}:web"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push api
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: poorprogrammer/cfo-api
          context: "{{defaultContext}}:api"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
